@extends('template.base')

@section('title','Terminos y Condiciones')

@section('content')

<div class="col-12 mt-3">
  <h1>Columbus</h1>
  <br>
  <h2>Términos de uso del sitio web</h2>
    <p>Bienvenido al sitio web de Columbus - www.Columbus.com, micrositio, sitio móvil (este "Sitio web") o aplicación móvil ("Aplicación"). Revise los siguientes términos y condiciones ("Términos y condiciones") antes de usar el Sitio web/la Aplicación. Los presentes Términos y condiciones, que se pueden modificar de vez en cuando, corresponden para todos los visitantes o usuarios del Sitio web/la Aplicación.</p>
  <h2>Su uso en general</h2>
    <p>Su uso del Sitio web y de la Aplicación confirma su aceptación de estos términos y condiciones y las obligaciones que estos conllevan. Si no acepta estos términos y condiciones, no utilice este Sitio web ni la Aplicación. En el caso de una violación de estos términos y condiciones, Columbus se reserva el derecho de recurrir a todas las reparaciones disponibles conforme a derecho o al sistema de equidad. Podemos cancelar su acceso o uso de este Sitio web y de esta Aplicación en cualquier momento, por cualquier motivo, o sin motivo alguno, y sin aviso previo. Eventualmente, podemos modificar estos Términos y condiciones al actualizar esta publicación. Debe visitar esta página de vez en cuando para leer los Términos y condiciones, tomar conocimiento y comprender las modificaciones, ya que son vinculantes para usted. Su uso de este Sitio web y de esta Aplicación después de estas modificaciones se interpretará como su aceptación de estos términos modificados y sus obligaciones.</p>
  <h2>Propiedad del contenido</h2>
    <p>El diseño de este Sitio web y de esta Aplicación y todo su material, incluidos, entre otros, software o código HTML, scripts, texto, material gráfico, fotografías, imágenes, diseños, video, audio, materiales escritos y otros que aparecen como parte de este Sitio web y de esta Aplicación (en conjunto, "Contenido") están protegidos por las leyes de derechos de autor de Argentina y otras leyes y tratados internacionales y de Argentina Todo el Contenido es proporcionado por Columbus bajo una licencia limitada como un servicio para sus clientes actuales y potenciales y solo puede ser utilizado para uso personal (es decir, para comprar nuestra mercancía). Esta licencia limitada está sujeta a las siguientes restricciones: (a) no podrá copiar, reproducir, hacer público, transmitir, distribuir, realizar, mostrar, publicar, modificar, crear obras derivadas, vender, otorgar licencias, permitir a terceros la copia o explotar de otro modo este Sitio web ni esta Aplicación ni su Contenido, o cualquier software relacionado; (b) no podrá acceder o usar este Sitio web y esta Aplicación con fines comerciales o de competencia. Se prohíbe toda copia, modificación, distribución, transmisión, realización, exhibición, venta u otro uso no autorizado del Contenido. Columbus puede revocar esta licencia limitada en cualquier momento y por cualquier motivo, o sin motivo alguno. Se prohíbe el uso no autorizado del Contenido de Columbus, como la integración, la vinculación u otra asociación con contenido o información que no se origine en el Sitio web y en la Aplicación de Columbus También se prohíbe el uso de enlaces a la página web de Columbus. Columbus hará valer sus derechos de propiedad intelectual hasta las últimas instancias previstas por la ley.</p>
  <h2>Marcas comerciales</h2>
    <p>En Columbus nos enorgullecemos de nuestra marca y no aprobamos ni toleramos el uso no autorizado de nuestras marcas comerciales, nombres comerciales, logos, nombres o la imagen de marca (en conjunto, las "Marcas comerciales e imagen de marca"). Columbus y sus compañías afiliadas conservan todos los derechos relacionados con las Marcas comerciales e imagen de marca. Éstas están protegidas por las leyes sobre marcas comerciales federales y estatales de Argentina, y leyes y tratados internacionales. No se le otorga ninguna licencia por el uso de las Marcas comerciales e imagen de marca, de acuerdo con estos términos y condiciones o por su uso del Sitio web o de la Aplicación. Está estrictamente prohibido todo uso no autorizado de nuestras Marcas comerciales e imagen de marca.</p>
  <h2>Nuestros productos</h2>
    <p>Todas las características, las especificaciones, los productos y los precios de productos y servicios detallados en este Sitio web y en esta Aplicación se encuentran sujetos a cambio en cualquier momento y sin previo aviso. Eventualmente, pueden aparecer errores tipográficos, imprecisiones u omisiones en la información del Sitio web y de la Aplicación que pueden relacionarse con descripciones de productos, precios y disponibilidad. No garantizamos la integridad, exactitud o actualidad de la información contenida en este Sitio web y en esta Aplicación. Nos reservamos el derecho de realizar cambios en la información sobre precios, descripciones o disponibilidad, sin previo aviso. Nos reservamos el derecho, sin previo aviso, de limitar la cantidad por pedido de cualquier producto y/o rechazar el servicio para cualquier cliente (consulte nuestros <a class="sale-terms-link" href="#">Términos de venta</a>). Nos esforzamos por mostrar los colores de los productos que aparecen en el Sitio web y en la Aplicación de la forma más precisa posible; sin embargo, el color real que vea dependerá de su dispositivo, y no podemos garantizar que reproduzca nuestros colores con precisión. La incorporación de productos o servicios en este Sitio web y en esta Aplicación no implica ni garantiza que estos productos o servicios estén disponibles en línea o en nuestras tiendas en un determinado momento.</p>
  <h2>Comentarios y otras comunicaciones</h2>
    <p>Los comentarios, opiniones, sugerencias, ideas u otras comunicaciones (en conjunto, "Comunicaciones") enviados a Columbus a través de este Sitio Web o de esta Aplicación con relación a su uso, o a través de email, correo postal, asistencia telefónica o cualquier forma de comunicación con nosotros, pasarán a ser propiedad de Columbus Columbus podrá utilizar ideas, conceptos, prácticas o técnicas incluidas en las Comunicaciones que nos ha enviado con cualquier finalidad, por ejemplo, entre otras, el desarrollo, la producción y la comercialización de productos mediante el uso de dicha información. Toda información de índole personal que suministra a Columbus a través del Sitio web o de la Aplicación estará sujeta a la <a class="privacy-policy-link" href="#">Política de privacidad</a>. Aquí se define "información de índole personal".</p>
  <h2>Contenido generado por el usuario</h2>
    <p><strong>Pautas para la publicación</strong></p>
    <p>El Sitio web puede permitir que cargue y/o publique contenido voluntariamente ("Contenido generado por el usuario"), que incluye fotografías, videos, comentarios y otro material. Si publica comentarios u otro tipo de texto, confirma que tiene al menos 14 años de edad o el permiso de sus padres/tutor; si publica fotografías o videos, confirma que tiene al menos 18 años de edad o el permiso de sus padres/tutor; y al publicar cualquier Contenido generado por el usuario, usted acepta los siguientes términos:</p>
    <p>(a) Publicar dicho Contenido generado por el usuario constituye que usted acepta y cede a Columbus el derecho y el permiso irrevocables, no exclusivos, perpetuos, globales, sin regalías, irrestrictos e ilimitados, pero no la obligación, de utilizar, reproducir, explotar, alterar, editar, modificar, distribuir, publicar, exhibir, digitalizar, emitir, mostrar, realizar de forma pública y preparar trabajos derivados del contenido generado por el usuario, su nombre, seudónimo, información de voz y biográfica, y cualquier tipo de material que se sustente o derive del mismo, en cualquier forma o medio que en el presente o subsecuentemente se conozca para cualquier propósito a nivel mundial que incluye, entre otros, fines publicitarios, de marketing o comerciales, sin realizar pago alguno ni autorización de su parte.</p>
    <p>(b) Usted renuncia a los derechos de inspeccionar o aprobar los materiales en que Columbus puede utilizar eventualmente su Contenido generado por el usuario, y además comprende que Columbus puede cortar, moldear o ajustar de otra manera dicho Contenido generado por el usuario.</p>
    <p>(c) Usted declara y garantiza que el Contenido generado por el usuario no violará los derechos de propiedad intelectual o los derechos de propiedad de terceros y que cuenta con la autorización legal para publicar el Contenido generado por el usuario y que cede todas las licencias y permisos relevantes para usar dicho Contenido de acuerdo con lo que se contempla en el presente.</p>
    <p>(d) Usted acepta no iniciar acciones legales en contra de, y liberar de toda responsabilidad a, Columbus, sus directores, personal jerárquico, empleados, representantes y afiliados, como así también a cualquier persona o entidad que actúe en su representación, si hubiera algún reclamo relacionado con el uso del Contenido generado por el usuario, su nombre, seudónimo, información de voz y biográfica, de acuerdo con lo contemplado en el presente.</p>
    <p>(e) Usted entiende y acepta que otras personas, incluso el público en general, pueden tener acceso y visualizar dicho Contenido generado por el usuario y que, si se publica o no dicho Contenido, Columbus no garantiza confidencialidad alguna con respecto a él. Usted es el único responsable de su propio Contenido generado, y las consecuencias de su publicación en este Sitio web o en cualquier otra plataforma (asumiendo que elegimos publicarlo una vez enviado). Nos reservamos el derecho de determinar según nuestro criterio si el Contenido generado por el usuario es adecuado; si cumple con los presentes Términos y condiciones, nuestras normas y la ley vigente; y si se puede publicar o eliminar.</p>
  <h2>Su cuenta</h2>
    <p>Puede elegir registrarse con nosotros a través de nuestro Sitio web o de nuestra Aplicación y crear una cuenta (la "Cuenta"). Si lo hace, tendrá acceso a su Cuenta al proporcionar una dirección de email y una contraseña. Usted es responsable de mantener la confidencialidad de su información de acceso y de controlar el acceso a su Cuenta y a su dispositivo. Usted acepta la responsabilidad por todas las actividades que se realicen en su Cuenta. Podemos cancelar su Cuenta en cualquier momento, por cualquier motivo, o sin motivo alguno, y sin aviso previo.</p>
  <h2>Enlaces</h2>
    <p>Se pueden crean enlaces desde este Sitio web y desde esta Aplicación a uno o más sitios web o recursos externos operados por terceros (los "Sitios de terceros"). Además, algunos Sitios web de terceros pueden contener enlaces a este Sitio web y a esta Aplicación. La incorporación de estos enlaces no debe ser interpretada como la validación por parte de Columbus de los Sitios de terceros o su contenido. Columbus no controla ni se hace responsable por los Sitios web de terceros ni de ningún contenido, publicidad, productos u otros materiales que aparezcan o estén disponibles en ellos. El acceso a los Sitios web de terceros se efecturá bajo su propio riesgo y Columbus no tendrá ninguna responsabilidad que surja de estos sitios web y/o de su contenido ni de ninguna pérdida ni daño causado, o supuestamente causado, por una compra, el uso o la confianza en el contenido, los bienes o servicios disponibles a través de estos Sitios web de terceros.</p>
  <h2>Descargo de responsabilidad</h2>
    <p>Este Sitio web, esta Aplicación y todo su Contenido son ofrecidos a nuestros clientes y clientes potenciales "TAL COMO SON" y "SEGÚN ESTÁN DISPONIBLES" y sin garantías de ningún tipo, ya sean expresas o implícitas, COMO, ENTRE OTRAS, GARANTÍAS CON RESPECTO A LA COMERCIALIZACIÓN, LA APTITUD PARA UN FIN PARTICULAR, EL TÍTULO O EL CUMPLIMIENTO. Usted acepta, mediante el uso del Sitio web y de la Aplicación, que su uso será bajo su exclusivo riesgo. Algunas jurisdicciones no permiten el descargo de responsabilidad por las garantías implícitas. En estas jurisdicciones, el descargo de responsabilidad antes mencionado no se aplicará.</p>
    <p>Usted comprende y acepta que, conforme a la Sección 230 de la Ley Federal de Decencia en las Comunicaciones de Argentina, los proveedores de servicios interactivos informáticos no serán tratados como editores o voceros de la información proporcionada por otro proveedor de contenidos.</p>
  <h2>Limitación de responsabilidad</h2>
    <p>BAJO NINGUNA CIRCUNSTANCIA Columbus SERÁ RESPONSABLE CON RESPECTO A UNA PARTE POR CUALQUIER DAÑO DIRECTO, INDIRECTO, FORTUITO, ESPECIAL, RESULTANTE O PUNITIVO POR EL USO DE ESTE SITIO WEB, DE ESTA APLICACIÓN U OTROS SITIOS WEB VINCULADOS COMO, ENTRE OTROS, PÉRDIDA DE GANANCIAS O INGRESOS, COSTOS DE REEMPLAZO, INTERRUPCIÓN EN LAS ACTIVIDADES COMERCIALES, PÉRDIDA DE DATOS O DAÑOS QUE RESULTEN DEL USO O LA CONFIANZA EN LA INFORMACIÓN EXPUESTA, INCLUSO SI Columbus FUERA EXPRESAMENTE NOTIFICADO ACERCA DE LA POSIBILIDAD DE DICHO DAÑO. En algunas jurisdicciones, no se permiten las limitaciones de responsabilidad. En estas jurisdicciones, las limitaciones de responsabilidad antes mencionadas no se aplicarán.</p>
  <h2>Jurisdicción</h2>
    <p>No se debe interpretar que los materiales publicados en este Sitio web y en esta Aplicación son adecuados para el uso fuera de los Argentina. Si accede a este Sitio web o a esta Aplicación desde fuera de los Argentina, lo hace por iniciativa propia y es responsable por el cumplimiento con las leyes locales. Columbus controla este Sitio web y esta Aplicación desde sus oficinas en la CABA. Los términos y condiciones de este Sitio web y de esta Aplicación serán regidos por las leyes de CABA, sin dar lugar a las disposiciones relativas a los conflictos de leyes.</p>
</div>

@endsection
